// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxrZMLcgr3vPpFbvfICYuMysudj_nRN0Q',
    appId: '1:955481732665:web:cd325dbbc5f6f407863fe8',
    messagingSenderId: '955481732665',
    projectId: 'flutter-first-4a269',
    authDomain: 'flutter-first-4a269.firebaseapp.com',
    storageBucket: 'flutter-first-4a269.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUsnrtao-aNdOzahucA0wCTwgrayOb-ws',
    appId: '1:955481732665:android:3952004c2500bcac863fe8',
    messagingSenderId: '955481732665',
    projectId: 'flutter-first-4a269',
    storageBucket: 'flutter-first-4a269.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3DVmuxr8LqtltXgZXxfpQphRB2sa3yAs',
    appId: '1:955481732665:ios:eb4319f02fd7672a863fe8',
    messagingSenderId: '955481732665',
    projectId: 'flutter-first-4a269',
    storageBucket: 'flutter-first-4a269.appspot.com',
    iosClientId: '955481732665-hhqpsrj4dhhqe1hgnh97obk9s2pvujlu.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
